include .env
.DEFAULT_GOAL := all

help:  ## show list of commands
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m\033[0m\n"} /^[$$()% 0-9a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

all: go-tidy docker-build docker-start db-upgrade build  ## build project

env:  ## copy .env.template into .env
	cp -n .env.template .env | true

generate-secret-key: # generate a key for JWT secrets
	openssl rand -base64 64

docker-build:  ## build the docker container via the docker-compose.yml file
	docker-compose build --no-cache

docker-start:  ## start the docker container
	docker-compose up --detach --remove-orphans

docker-stop:  ## stop the docker container
	docker-compose stop

docker-down:  ## stop the docker container and remove containers, entworks, volumes, and images
	docker-compose down --remove-orphans

db-makemigrations:  ## generate a database migration file with atlas
	atlas migrate diff --env gorm

db-upgrade:  ## migrate the database using the generated atlas migration file
	atlas migrate apply --dir "file://internal/database/migrations" --url "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"

db-downgrade:  ## downgrade the database using the generated atlas migration file
	atlas migrate down --dev-url="docker://postgres/15/dev" --dir "file://internal/database/migrations" --url "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"

db-terminal:  ## open a psql terminal in the runniing docker container
	docker exec -it go-jwt-rest-api-db psql -d ${DB_NAME} -U ${DB_USER}

swagger-build:  ## build swagger docs
	go tool swag init --dir cmd/go-jwt-rest-api,./ --parseDependency --generalInfo ../../internal/handlers/docs.go

swagger-fix: swagger-build  ## fix swagger docs (e.g. "null" -> null)
	./docs/fix.sh

go-tidy:  ## update go.mod and download necessary dependencies
	go mod tidy

go-build-dev:  ## compiles the program into ./tmp/main for live reload
	go build -o ./tmp/main ./cmd/go-jwt-rest-api/main.go

go-build:  ## compiles the program
	go build -o ./bin/main ./cmd/go-jwt-rest-api/main.go

runserver r:  ## runs the server locally with live reload. configuration options in .air.toml
	go tool air

test:  ## run tests
	go test ./... | go tool tc

lint:  ## apply linting to files
	go tool golines -w .

build: swagger-build swagger-fix go-build-dev  ## build target for air

clean:  ## remove temporary and autogenerated files
	rm -rf ./tmp
	rm -rf ./bin
	rm -f ./docs/swagger.*
