// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/invites": {
            "get": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Get a list of all invited, but not registered, users",
                "tags": [
                    "admin"
                ],
                "summary": "get all invited users",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOKList"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/invites/create": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Creates a InvitedUser with an email address and temporary password. Invited user must use this email and password to register for an account.",
                "tags": [
                    "admin"
                ],
                "summary": "create an invitation for a new user",
                "parameters": [
                    {
                        "description": "Invitation email and password",
                        "name": "invitationInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusCreated"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/invites/delete/{user_id}": {
            "delete": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Delete an invited user",
                "tags": [
                    "admin"
                ],
                "summary": "delete invited user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (uuid)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/invites/reset-password": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Reset the password of an invited user in case password was forgotten.",
                "tags": [
                    "admin"
                ],
                "summary": "reset the password of an invited user",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "loginInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/manage/add-admin/{user_id}": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Elevate the given user's role to ` + "`" + `admin` + "`" + `.",
                "tags": [
                    "admin"
                ],
                "summary": "upgrade a user to admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of user to elevate to admin",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusCreated"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/manage/create-initial-admin": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "When no users exist in the database, create an admin user with the given information.",
                "tags": [
                    "admin"
                ],
                "summary": "create first user as admin",
                "parameters": [
                    {
                        "description": "Admin registration information",
                        "name": "registrationInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.AdminRegister"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusCreated"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/manage/remove-admin/{user_id}": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Remove admin permissions from user. POST body requires current admin user's email and password for verification.",
                "tags": [
                    "admin"
                ],
                "summary": "downgrade an admin to user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of admin to downgrade to user",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusCreated"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Get a list of all registered users",
                "tags": [
                    "admin"
                ],
                "summary": "get all users",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOKList"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/users/delete/{user_id}": {
            "delete": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Delete a user",
                "tags": [
                    "admin"
                ],
                "summary": "delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (uuid)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/admin/users/reset-password": {
            "post": {
                "security": [
                    {
                        "AdminAccessInCookie": []
                    }
                ],
                "description": "Reset the password of a user in case password was forgotten.",
                "tags": [
                    "admin"
                ],
                "summary": "reset the password of a user",
                "parameters": [
                    {
                        "description": "New login info",
                        "name": "loginInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "UserAccessCookie": []
                    }
                ],
                "description": "Given correct login information, allow user to change their password.",
                "tags": [
                    "auth"
                ],
                "summary": "change user password",
                "parameters": [
                    {
                        "description": "New login info",
                        "name": "changeLoginInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserPasswordChange"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Logs in user with given email and password.\n\nOn success, returns status code 200 and sends back HTTPOnly access and refresh tokens.",
                "tags": [
                    "auth"
                ],
                "summary": "login registered user",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "loginInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "UserAccessCookie": []
                    }
                ],
                "description": "Logs out user by removing access_token and refresh_token cookies",
                "tags": [
                    "auth"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "security": [
                    {
                        "UserAccessCookie": []
                    }
                ],
                "description": "Reads the user's refresh_token cookie and sends back a new access_token.\n\nNot allowed if tokens are refreshed on the backend (` + "`" + `JWT_BACKEND_REFRESH` + "`" + ` environment variable).",
                "tags": [
                    "auth"
                ],
                "summary": "refresh access token from refresh token",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "tags": [
                    "health check"
                ],
                "summary": "API Health Check",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "registration"
                ],
                "summary": "register new user",
                "parameters": [
                    {
                        "description": "Registration Information",
                        "name": "registrationInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusCreated"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "UserAccessCookie": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "get user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (uuid)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "UserAccessCookie": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "update user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (uuid)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user info",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "schema": {
                            "$ref": "#/definitions/http.StatusOK"
                        }
                    },
                    "400": {
                        "description": "Status Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "401": {
                        "description": "Status Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "403": {
                        "description": "Status Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "404": {
                        "description": "Status Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    },
                    "500": {
                        "description": "Status Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.StatusError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.UserLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "aPassword1!"
                }
            }
        },
        "auth.UserPasswordChange": {
            "type": "object",
            "required": [
                "email",
                "new_password",
                "new_password_confirm",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "new_password": {
                    "type": "string",
                    "example": "newPassword2!"
                },
                "new_password_confirm": {
                    "type": "string",
                    "example": "newPassword2!"
                },
                "password": {
                    "type": "string",
                    "example": "aPassword1!"
                }
            }
        },
        "http.StatusCreated": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "id-of-created-object"
                },
                "message": {
                    "type": "string",
                    "example": "created successfully"
                }
            }
        },
        "http.StatusError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "http.StatusOK": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.StatusOKList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "user.AdminRegister": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Chosen email address",
                    "type": "string",
                    "example": "admin@example.com"
                },
                "first_name": {
                    "description": "Chosen first name",
                    "type": "string",
                    "example": "FirstName"
                },
                "last_name": {
                    "description": "Chosen last name",
                    "type": "string",
                    "example": "LastName"
                },
                "password": {
                    "description": "Chosen password.\nMust be 8\u003e= len \u003e= 64 characters, contain at least one uppercase, one lowercase, one digit, one special character",
                    "type": "string",
                    "example": "adminPassword123!"
                },
                "username": {
                    "description": "Chosen username",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "user.RoleEnum": {
            "type": "string",
            "enum": [
                "admin",
                "user"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser"
            ]
        },
        "user.User": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "username"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "description": "User's email address",
                    "type": "string",
                    "example": "username@example.com"
                },
                "first_name": {
                    "description": "User's first name",
                    "type": "string",
                    "example": "FirstName"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "description": "User's last name",
                    "type": "string",
                    "example": "LastName"
                },
                "role": {
                    "description": "User's role -- oneof \"user\", \"admin\"",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.RoleEnum"
                        }
                    ],
                    "example": "admin"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "description": "User's username",
                    "type": "string",
                    "example": "username"
                }
            }
        },
        "user.UserRegister": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "new_password",
                "new_password_confirm",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Email of invited user, given when invited",
                    "type": "string",
                    "example": "user@example.com"
                },
                "first_name": {
                    "description": "invited user's chosen first name",
                    "type": "string",
                    "example": "FirstName"
                },
                "last_name": {
                    "description": "invited user's chosen last name",
                    "type": "string",
                    "example": "LastName"
                },
                "new_password": {
                    "description": "invited user's chosen new password\nMust be 8\u003e= len \u003e= 64 characters, contain at least one uppercase, one lowercase, one digit, one special character",
                    "type": "string",
                    "example": "user-chosen-password"
                },
                "new_password_confirm": {
                    "description": "Confirmation of chosen password\nMust be 8\u003e= len \u003e= 64 characters, contain at least one uppercase, one lowercase, one digit, one special character",
                    "type": "string",
                    "example": "user-chosen-password"
                },
                "password": {
                    "description": "Temporary password of invited user, given when invited",
                    "type": "string",
                    "example": "password-given-to-invited-user"
                },
                "username": {
                    "description": "invited user's chosen username",
                    "type": "string",
                    "example": "user"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Requires logged in user to be an admin. Don't actually fill this out! Use the /login endpoint with an admin user instead.",
            "type": "apiKey",
            "name": "AdminAccessInCookie",
            "in": "cookie"
        },
        "BasicAuth": {
            "description": "Requires login. Don't actually fill this out! Use the /login endpoint.",
            "type": "apiKey",
            "name": "UserAccessCookie",
            "in": "cookie"
        }
    },
    "tags": [
        {
            "name": "health check"
        },
        {
            "description": "login, logout, and refresh token",
            "name": "auth"
        },
        {
            "description": "register as an invited user",
            "name": "registration"
        },
        {
            "description": "view and update user information",
            "name": "users"
        },
        {
            "description": "admin user capabilities",
            "name": "admin"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "JWT Cookie Rest",
	Description:      "Rest API for JWT cookie authentication and user registration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
